# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Part 6 CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  PORT: ${{ secrets.PORT }}
  SECRET: ${{ secrets.SECRET }}

defaults:
  run:
    working-directory: part6

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          working-directory: ./app
      - run: cd unicafe
      - run: npm config set fund false
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: cd ..